In [2]:
import tensorflow as tf

## Sequential Model

In [11]:
%%html
<img src='layer.PNG' style='width:60%'/>

In [12]:
model = tf.keras.Sequential()

In [14]:
model.add(
    tf.keras.layers.Dense(32, input_shape=(10,), activation='relu')
)

In [15]:
model.add(
    tf.keras.layers.Dense(2, activation='softmax')
)

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                352       
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 66        
Total params: 418
Trainable params: 418
Non-trainable params: 0
_________________________________________________________________


In [18]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(32, input_shape=(10,), activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

In [19]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 32)                352       
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 66        
Total params: 418
Trainable params: 418
Non-trainable params: 0
_________________________________________________________________


In [21]:
input_tensor = tf.keras.layers.Input(shape=(10,), dtype='int32')

In [22]:
x = tf.keras.layers.Dense(32, activation='relu')(input_tensor)
y= tf.keras.layers.Dense(2, activation='softmax')(x)


In [25]:
model = tf.keras.Model(input_tensor, outputs=y)

In [26]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10)]              0         
_________________________________________________________________
dense_6 (Dense)              (None, 32)                352       
_________________________________________________________________
dense_7 (Dense)              (None, 2)                 66        
Total params: 418
Trainable params: 418
Non-trainable params: 0
_________________________________________________________________


## Optimizer/loss/cost/accuracy

In [27]:
optimizer = tf.keras.optimizers.Adam(0.01)

In [38]:
loss = tf.keras.losses.CategoricalCrossentropy()

In [40]:
acc = tf.keras.metrics.CategoricalAccuracy('accuracy')

In [51]:
model.compile(optimizer, loss=loss, metrics=[acc])

In [52]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10)]              0         
_________________________________________________________________
dense_6 (Dense)              (None, 32)                352       
_________________________________________________________________
dense_7 (Dense)              (None, 2)                 66        
Total params: 418
Trainable params: 418
Non-trainable params: 0
_________________________________________________________________


## tensors

In [56]:
import pandas as pd
import numpy as np


In [60]:
inputs = [0,1,2,3]
labels = [1,0,1,0]

In [61]:
dataset = tf.data.Dataset.from_tensor_slices((inputs, labels))

In [59]:
for item in dataset:
    print(item)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [62]:
inputs = np.asarray(inputs)
labels = np.asarray(labels)

In [64]:
inputs, labels

(array([0, 1, 2, 3]), array([1, 0, 1, 0]))

In [65]:
dataset = tf.data.Dataset.from_tensor_slices((inputs, labels))

In [66]:
for item in dataset:
    print(item)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
